# Generated by Django 4.0.5 on 2022-06-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('address', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='PICTURE')),
            ],
        ),
    ]
