# Generated by Django 4.0.4 on 2022-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('classs', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('address', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='PICTURE')),
            ],
        ),
    ]
